### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.3

### PR DESCRIPTION
**Pull request by jdblischak**

### CODE REVIEW

**Comment by bgruening** [comment]
John maybe we should check for those PR that don't do much and avoid them? It seems to waste a lot of CPU cycles.

**Comment by jdblischak** [comment]
@bgruening I understand that this PR does not look that useful given the changes to the files. However, the changes are not that important (an empty commit would have worked too). This package was not available for R 3.4.1 on osx-64. This is likely due to missing dependencies when the feedstock was created (due to the race condition when multiple R recipes are included in the same PR to staged-recipes). The CPU cycles spent on the PR confirm that the dependencies have been satisfied, and the CPU cycles spent on the merged commit uploaded the R 3.4.1 osx-64 package to Anaconda Cloud:

https://anaconda.org/conda-forge/r-formattable/files

I agree that CPU cycles could be saved by manually re-starting only the specific CI build that had failed. But there are about 100 conda-forge recipes that are available for R 3.3.2 and not R 3.4.1 (or vice versa). If a few of us are going to be able to maintain 500+ R packages, I think we have to be willing to waste some CPU cycles in order to automate these tasks. I didn't manually rerender 25 feedstocks last night. I ran this [script](https://github.com/jdblischak/jdb-conda/blob/master/scripts/rerender-r-packages.R).

Do you agree? Is there a different method you would prefer I use?

**Comment by bgruening** [comment]
We could simply re-start the failing CI jobs.

**Comment by jdblischak** [comment]
> We could simply re-start the failing CI jobs.

OK. How about instead of submitting a PR, I instead open an Issue for repositories that only need re-started? I think we need some way to keep track of this.

**Comment by bgruening** [comment]
Sounds good. Or we can have a meta issue.
Don't get me wrong, I love these PRs I'm just concerned about the CIs.

**Comment by jdblischak** [comment]
That's doable. I'll check to see how many lines the rerendering changed. If it was fewer than a couple lines, I'll have the script open an Issue as opposed to a PR.

I'd prefer to open Issues on each feedstock individually rather than a meta Issue. The reason is that because of dependencies, some feedstocks shouldn't be restarted yet. I'll have the script only open an Issue on feedstocks that are ready to be restarted.

**Pull request merged**
